### ISSUE TITLE
Understanding CSS.RuleUsageTracking stuff

### ISSUE THREAD

**Issue by yarikbratashchuk** [ChromeDevTools/devtools-protocol#21]
Hello)

I tried to use CSS.RuleUsageTracking methods and CSS.takeCoverageDelta to get all css rules needed to render a page. I expected to get all css rules needed to render a page, but unfortunately it doesn't work. I got some css rules, but not all, because the page looks ugly if to apply them.

First i run ```CSS.startRuleUsageTracking```,
then i load the page,
and then (with 25sec timeout) i run ```CSS.stopRuleUsageTracking```
and then i get css rules using ```RuleUsage``` array (response from ```CSS.stopRuleUsageTracking```)

Does it work the way i expect? or i go wrong with this stuff? Could U tell me what should i use to get all css rules needed for page to render for the first time? 

Thanks a lot)

**Comment by yarikbratashchuk** [comment]
Does somebody can help me with this?

Thanks a lot.

**Comment by caseq** [comment]
Yes, it does work as you describe and it looks like you're doing it right. This is generally expected to produce the list of rules that would be sufficient to render the page, as long as your scenario ensures that rules conditional on media queries or used by contents shown as a result of various user actions (e.g. popups & co) are also hit. There are, however, a  few cases that are not yet covered -- apparently, @font-face declarations are not properly handled (https://crbug.com/744202) and CSS imports are not processed (https://crbug.com/734470).
If the problems you're observing are not because of those, please try to make a reduction of the page and file this a bug on crbug.com.

Best regards,
Andrey.

**Comment by paulirish** [comment]
FWIW Here's what devtools frontend is doing under the hood:

https://github.com/ChromeDevTools/devtools-frontend/blob/master/front_end/coverage/CoverageModel.js#L147-L176

**Comment by yarikbratashchuk** [comment]
instead of a thousand words) thanks)
