### ISSUE TITLE
Puppeteer and Nexe compilie

### ISSUE THREAD

**Issue by ameyohu** [ChromeDevTools/devtools-protocol#226]
First time poster, - sorry if this isn't the right place for this question

Hi, guys i am trying to compilie nodejs puppeteer with npm nexe .everthing works with puppeteer 2.2.1.
If i try to compile with more recent release 3.2.0 4.0.0 5.3.0 i get this error when i try to run .exe file.
it's not a big problem "currnetly" but it got really intresting , i tried to investigate - no success.

any help will be appreciated.

this is how i build with nexe 
 nexe build -t x64-8.0.0 -o test1.exe
 

E:\Botings\WAITINGBOX\node_modules\puppeteer\lib\BrowserFetcher.js:394
        ...urlParsed,
        ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (E:\Botings\WAITINGBOX\node_modules\puppeteer\lib\api.js:24:21)

**Comment by TimvdLippe** [comment]
I think this is a Puppeteer issue, which you can file at https://github.com/puppeteer/puppeteer That said, from your description I understand you are trying to compile the output of Puppeteer. Since Puppeteer is already compiled, you should not recompile.

If you are trying to use the build output from Puppeteer, make sure that the tool you are using supports modern JavaScript. In this case, you probably want to verify that `nexe` supports the spread operator.

**Comment by patrickhulce** [comment]
@ameyohu puppeteer dropped support for node 8 in those versions, use a newer version of node in your nexe compilation

**Comment by ameyohu** [comment]
Thanks guy
@patrickhulce using node 14.12 same error
