### ISSUE TITLE
How to get repainted dom list that use devtools-protocol API?

### ISSUE THREAD

**Issue by mixed** [ChromeDevTools/devtools-protocol#23]
[I want to find unnecessary offscreen repainted gifs(dom).](https://www.html5rocks.com/en/tutorials/speed/animated-gifs/) I can see repainted dom using `Overlay.setShowPaintRects`. but I can't get repainted dom list using devtools-protocol. How to get repainted dom list using devtools-protocol?

Thanks.

**Comment by pavelfeldman** [comment]
We only have this information as a part of the trace (Tracing.start/stop) with certain tracing categories enabled. Exposing it over the protocol requires some interesting plumbing. What are you using this information for?

**Comment by leesnhyun** [comment]
In my case, I would like to use it to obtain the position information of the DOM objects that is changing.
( I don't want to do DOM tree diff with for-loop if multiple DOM objects are horizontally placed )

 Of course, I have found that the category 'blink.debug.layout.trees' has returned the layout-tree(render tree) that Blink has calculated, as @pavelfeldman mentioned. However, I'm concerned because I can not check the tracing results in real time.

**Comment by TimvdLippe** [comment]
This repository is related to Chrome DevTools Protocol, but does not track issues regarding its definition or implementation. If you want to file an issue for the Chrome DevTools Protocol, please open an issue on https://crbug.com under [`component: Platform>DevTools>Platform`](https://bugs.chromium.org/p/chromium/issues/entry?components=Platform%3EDevTools%3EPlatform). Thanks in advance!
