### ISSUE TITLE
RuleUsage startOffset and endOffset seem to be incorrect

### ISSUE THREAD

**Issue by mziemer21** [ChromeDevTools/devtools-protocol#65]
I am trying to add CSS coverage using [CSS.startRuleUsageTracking](https://chromedevtools.github.io/devtools-protocol/tot/CSS/#method-getBackgroundColors) to this [covfefe-coverage](https://github.com/paulirish/covfefe-coverage) example. I am getting an array of [RuleUsage items](https://chromedevtools.github.io/devtools-protocol/tot/CSS/#type-RuleUsage), but when I try and match a rule's startOffset and endOffset to the origin css file I am getting incomplete css rules.
```
 article a[name]:hover {
  text-decoration: none
}
.waffle-sample .o
```
^^ start of a new rule that is cut off

Here is a gist of my launchChrome function.
https://gist.github.com/mziemer21/5b76d5e695501af72272d40c9e693a43

Am I incorrect assuming startOffset and endOffset can be used as substring params on the original css file ([line 29](https://gist.github.com/mziemer21/5b76d5e695501af72272d40c9e693a43#file-csscoverage-js-L29))?

**Comment by paulirish** [comment]
cc @caseq who knows for sure.

I thought this may be an off-by-one issue, but now not so sure.

Take a look at [CoverageModel.js](https://github.com/ChromeDevTools/devtools-frontend/blob/master/front_end/coverage/CoverageModel.js) and `_convertToDisjointSegments()` which postprocesses the ranges that come back from the protocol.

**Comment by karanjthakkar** [comment]
@mziemer21 Would you mind sharing the css file contents for which you're facing this?

Also, did you happen to check the coverage in chrome devtools `Coverage` tab by opening that page in the browser? Does that also show it incorrectly?

**Comment by caseq** [comment]
May I suggest a different MDN page as a better example? :-)

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substr

You're using the following code to extract the matching fragment in line 29:

cssFile.text.substr(cssRule.startOffset, cssRule.endOffset);

endOffset is an offset from the start of stylesheet, substr() accepts
length as a second argument. You're getting 17 extra characters because
your startOffset is 17.

Best regards,
Andrey.


The

**Comment by mziemer21** [comment]
:sweat_smile: Thanks for catching that @caseq! **substring()** gives me valid rules.
