### ISSUE TITLE
Nodejs Inspector not stopping at breakpoints

### ISSUE THREAD

**Issue by govindrai** [ChromeDevTools/devtools-protocol#85]
I have the `debugger` keyword placed in multiple places in my file, and have even added manual breakpoints in the inspector UI. Still, executing the file does not stop at any breakpoints. I am using node 9.2.0 and chrome 64.0.3282.167.

Here is a picture of how my devtools appears.
![screen shot 2018-02-26 at 10 24 56 am](https://user-images.githubusercontent.com/13859249/36688371-19656aea-1ae1-11e8-8083-9320e98cd48f.png)

**Comment by ak239** [comment]
What flag do you use to start Node with inspector? --inpsect or --inspect-brk?

**Comment by govindrai** [comment]
@ak239 I ran it with --inspect. --inspect-brk makes it work but if you have the time, could you explain why the inspector cannot pick up breakpoints without it?

**Comment by ak239** [comment]
We are working on better workflow here but for now --inspect-brk is only one way.
With --inspect-brk node waits DevTools frontend connection. On connection DevTools send all breakpoints information and starts JavaScript execution in node.
With --inspect node starts JavaScript execution without waiting for DevTools frontend. As soon as DevTools connected, we send the same breakpoint information to node but it can be too late since some JavaScript is already executed.

**Comment by govindrai** [comment]
Thank you for you help! Closing this!

**Comment by tasoss** [comment]
Hello.
Because of the fact that inspect brk doesn't work , what do u propose?
I mean this thing used to work and it was great.It's really hard to debug on big projects.
Does changing node or chrome can solve this so at least,i will be able to debug?
Thanks!

**Comment by paramsinghvc** [comment]
What's the solution here. Why is it closed? 
@ak239 Can you please suggest some workaround for the same. The debugger is not pausing on the breakpoints in chrome devtool.

**Comment by llwanghong** [comment]
run into the same issue, seems can only use vscode debug or downgrade
chrome browser version.

**Comment by paramsinghvc** [comment]
In Chrome Canary 72, it works. @llwanghong

**Comment by viksok** [comment]
Updated to Chrome 72.0.3626.96 /Ubuntu yesterday and it stopped working.
Neither --inspect nor --inspect-brk doesn't work.

**Comment by Gobliins** [comment]
Missing breakpoints sometimes on Win Version 72.0.3626.109 (Official Build) (64-Bit)

**Comment by june07** [comment]
https://blog.june07.com/nim-custom-devtools-url explains a solution to this. Often the problem is due to breaking changes with DevTools. Using NiM allows you to lock the DevTools version whilst still using the most recent version of Chrome.

**Comment by ak239** [comment]
I suggest to use latest Chrome DevTools and file a bug on [crbug.com](crbug.com) when something does not work. In this case you get all new features and help other developers to get best experience.

Latest Node 12 should work well with latest Chrome DevTools frontend. Here is a link how to use dedicated devtools frontend: https://medium.com/@paul_irish/debugging-node-js-nightlies-with-chrome-devtools-7c4a1b95ae27

**Comment by june07** [comment]
Couldn't agree with @ak239 more.

With NiM I can use DevTools latest or a different version if I need, so while I'm filing my bug on [crbug.com](https://github.com/ChromeDevTools/devtools-protocol/issues/crbug.com), I'm not blocked and can continue my own work:
![https://i.imgur.com/ofYxhQo.gif](https://i.imgur.com/ofYxhQo.gif)

I like using the latest and greatest version of DevTools whenever possible because the DevTools team is always improving it!  As Paul brings out in the Youtube link ak239 shared: https://medium.com/@paul_irish/debugging-node-js-nightlies-with-chrome-devtools-7c4a1b95ae27, tools like NiM simply help in using the Chrome DevTools workflow.
